site_name: FNA Docs

repo_url: https://github.com/FNA-XNA/docs
site_description: Documentation for FNA
edit_uri: blob/main/docs/

theme:
  name: readthedocs
  logo: img/logo.png
  
extra_css: 
  - css/styles.css
